eval_levels:
  [
    "eval_grasper/grasp_hard_xvar_v0000.json",
    "eval_grasper/grasp_hard_xvar_v0001.json",
    "eval_grasper/grasp_hard_xvar_v0002.json",
    "eval_grasper/grasp_hard_xvar_v0003.json",
    "eval_grasper/grasp_hard_xvar_v0004.json",
    "eval_grasper/grasp_hard_xvar_v0005.json",
    "eval_grasper/grasp_hard_xvar_v0006.json",
    "eval_grasper/grasp_hard_xvar_v0007.json",
    "eval_grasper/grasp_hard_xvar_v0008.json",
    "eval_grasper/grasp_hard_xvar_v0009.json",
    "eval_grasper/grasp_hard_xvar_v0010.json",
    "eval_grasper/grasp_hard_xvar_v0011.json",
    "eval_grasper/grasp_hard_xvar_v0012.json",
    "eval_grasper/grasp_hard_xvar_v0013.json",
    "eval_grasper/grasp_hard_xvar_v0014.json",
    "eval_grasper/grasp_hard_xvar_v0015.json",
    "eval_grasper/grasp_hard_xvar_v0016.json",
    "eval_grasper/grasp_hard_xvar_v0017.json",
    "eval_grasper/grasp_hard_xvar_v0018.json",
    "eval_grasper/grasp_hard_xvar_v0019.json",
    "eval_grasper/grasp_hard_xvar_v0020.json",
    "eval_grasper/grasp_hard_xvar_v0021.json",
    "eval_grasper/grasp_hard_xvar_v0022.json",
    "eval_grasper/grasp_hard_xvar_v0023.json",
    "eval_grasper/grasp_hard_xvar_v0024.json",
    "eval_grasper/grasp_hard_xvar_v0025.json",
    "eval_grasper/grasp_hard_xvar_v0026.json",
    "eval_grasper/grasp_hard_xvar_v0027.json",
    "eval_grasper/grasp_hard_xvar_v0028.json",
    "eval_grasper/grasp_hard_xvar_v0029.json",
    "eval_grasper/grasp_hard_xvar_v0030.json",
    "eval_grasper/grasp_hard_xvar_v0031.json",
    "eval_grasper/grasp_hard_xvar_v0032.json",
    "eval_grasper/grasp_hard_xvar_v0033.json",
    "eval_grasper/grasp_hard_xvar_v0034.json",
    "eval_grasper/grasp_hard_xvar_v0035.json",
    "eval_grasper/grasp_hard_xvar_v0036.json",
    "eval_grasper/grasp_hard_xvar_v0037.json",
    "eval_grasper/grasp_hard_xvar_v0038.json",
    "eval_grasper/grasp_hard_xvar_v0039.json",
    "eval_grasper/grasp_hard_xvar_v0040.json",
    "eval_grasper/grasp_hard_xvar_v0041.json",
    "eval_grasper/grasp_hard_xvar_v0042.json",
    "eval_grasper/grasp_hard_xvar_v0043.json",
    "eval_grasper/grasp_hard_xvar_v0044.json",
    "eval_grasper/grasp_hard_xvar_v0045.json",
    "eval_grasper/grasp_hard_xvar_v0046.json",
    "eval_grasper/grasp_hard_xvar_v0047.json",
    "eval_grasper/grasp_hard_xvar_v0048.json",
    "eval_grasper/grasp_hard_xvar_v0049.json",
  ]
eval_num_attempts: 20
eval_freq: 10
EVAL_ON_SAMPLED: false
