train_level_mode: list
train_levels_list:
  [
    "green_pos/grasp_easy_pos_v0000.json",
    "green_pos/grasp_easy_pos_v0001.json",
    "green_pos/grasp_easy_pos_v0002.json",
    "green_pos/grasp_easy_pos_v0003.json",
    "green_pos/grasp_easy_pos_v0004.json",
    "green_pos/grasp_easy_pos_v0005.json",
    "green_pos/grasp_easy_pos_v0006.json",
    "green_pos/grasp_easy_pos_v0007.json",
    "green_pos/grasp_easy_pos_v0008.json",
    "green_pos/grasp_easy_pos_v0009.json",
    "green_pos/grasp_easy_pos_v0010.json",
    "green_pos/grasp_easy_pos_v0011.json",
    "green_pos/grasp_easy_pos_v0012.json",
    "green_pos/grasp_easy_pos_v0013.json",
    "green_pos/grasp_easy_pos_v0014.json",
    "green_pos/grasp_easy_pos_v0015.json",
    "green_pos/grasp_easy_pos_v0016.json",
    "green_pos/grasp_easy_pos_v0017.json",
    "green_pos/grasp_easy_pos_v0018.json",
    "green_pos/grasp_easy_pos_v0019.json",
    "green_pos/grasp_easy_pos_v0020.json",
    "green_pos/grasp_easy_pos_v0021.json",
    "green_pos/grasp_easy_pos_v0022.json",
    "green_pos/grasp_easy_pos_v0023.json",
    "green_pos/grasp_easy_pos_v0024.json",
    "green_pos/grasp_easy_pos_v0025.json",
    "green_pos/grasp_easy_pos_v0026.json",
    "green_pos/grasp_easy_pos_v0027.json",
    "green_pos/grasp_easy_pos_v0028.json",
    "green_pos/grasp_easy_pos_v0029.json",
    "green_pos/grasp_easy_pos_v0030.json",
    "green_pos/grasp_easy_pos_v0031.json",
    "green_pos/grasp_easy_pos_v0032.json",
    "green_pos/grasp_easy_pos_v0033.json",
    "green_pos/grasp_easy_pos_v0034.json",
    "green_pos/grasp_easy_pos_v0035.json",
    "green_pos/grasp_easy_pos_v0036.json",
    "green_pos/grasp_easy_pos_v0037.json",
    "green_pos/grasp_easy_pos_v0038.json",
    "green_pos/grasp_easy_pos_v0039.json",
    "green_pos/grasp_easy_pos_v0040.json",
    "green_pos/grasp_easy_pos_v0041.json",
    "green_pos/grasp_easy_pos_v0042.json",
    "green_pos/grasp_easy_pos_v0043.json",
    "green_pos/grasp_easy_pos_v0044.json",
    "green_pos/grasp_easy_pos_v0045.json",
    "green_pos/grasp_easy_pos_v0046.json",
    "green_pos/grasp_easy_pos_v0047.json",
    "green_pos/grasp_easy_pos_v0048.json",
    "green_pos/grasp_easy_pos_v0049.json",
    "green_pos/grasp_easy_pos_v0050.json",
    "green_pos/grasp_easy_pos_v0051.json",
    "green_pos/grasp_easy_pos_v0052.json",
    "green_pos/grasp_easy_pos_v0053.json",
    "green_pos/grasp_easy_pos_v0054.json",
    "green_pos/grasp_easy_pos_v0055.json",
    "green_pos/grasp_easy_pos_v0056.json",
    "green_pos/grasp_easy_pos_v0057.json",
    "green_pos/grasp_easy_pos_v0058.json",
    "green_pos/grasp_easy_pos_v0059.json",
    "green_pos/grasp_easy_pos_v0060.json",
    "green_pos/grasp_easy_pos_v0061.json",
    "green_pos/grasp_easy_pos_v0062.json",
    "green_pos/grasp_easy_pos_v0063.json",
    "green_pos/grasp_easy_pos_v0064.json",
    "green_pos/grasp_easy_pos_v0065.json",
    "green_pos/grasp_easy_pos_v0066.json",
    "green_pos/grasp_easy_pos_v0067.json",
    "green_pos/grasp_easy_pos_v0068.json",
    "green_pos/grasp_easy_pos_v0069.json",
    "green_pos/grasp_easy_pos_v0070.json",
    "green_pos/grasp_easy_pos_v0071.json",
    "green_pos/grasp_easy_pos_v0072.json",
    "green_pos/grasp_easy_pos_v0073.json",
    "green_pos/grasp_easy_pos_v0074.json",
    "green_pos/grasp_easy_pos_v0075.json",
    "green_pos/grasp_easy_pos_v0076.json",
    "green_pos/grasp_easy_pos_v0077.json",
    "green_pos/grasp_easy_pos_v0078.json",
    "green_pos/grasp_easy_pos_v0079.json",
    "green_pos/grasp_easy_pos_v0080.json",
    "green_pos/grasp_easy_pos_v0081.json",
    "green_pos/grasp_easy_pos_v0082.json",
    "green_pos/grasp_easy_pos_v0083.json",
    "green_pos/grasp_easy_pos_v0084.json",
    "green_pos/grasp_easy_pos_v0085.json",
    "green_pos/grasp_easy_pos_v0086.json",
    "green_pos/grasp_easy_pos_v0087.json",
    "green_pos/grasp_easy_pos_v0088.json",
    "green_pos/grasp_easy_pos_v0089.json",
    "green_pos/grasp_easy_pos_v0090.json",
    "green_pos/grasp_easy_pos_v0091.json",
    "green_pos/grasp_easy_pos_v0092.json",
    "green_pos/grasp_easy_pos_v0093.json",
    "green_pos/grasp_easy_pos_v0094.json",
    "green_pos/grasp_easy_pos_v0095.json",
    "green_pos/grasp_easy_pos_v0096.json",
    "green_pos/grasp_easy_pos_v0097.json",
    "green_pos/grasp_easy_pos_v0098.json",
    "green_pos/grasp_easy_pos_v0099.json",
  ]
