train_level_mode: list
train_levels_list:
  [
    "hard_pos_100_y_indix/grasp_hard_indepy_v0000.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0001.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0002.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0003.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0004.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0005.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0006.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0007.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0008.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0009.json",
  ]
