train_level_mode: list
train_levels_list:
  [
    "hard_pos_100_y_indix/grasp_hard_indepy_v0000.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0001.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0002.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0003.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0004.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0005.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0006.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0007.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0008.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0009.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0010.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0011.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0012.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0013.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0014.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0015.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0016.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0017.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0018.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0019.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0020.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0021.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0022.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0023.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0024.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0025.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0026.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0027.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0028.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0029.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0030.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0031.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0032.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0033.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0034.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0035.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0036.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0037.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0038.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0039.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0040.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0041.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0042.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0043.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0044.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0045.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0046.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0047.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0048.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0049.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0050.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0051.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0052.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0053.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0054.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0055.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0056.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0057.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0058.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0059.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0060.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0061.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0062.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0063.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0064.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0065.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0066.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0067.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0068.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0069.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0070.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0071.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0072.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0073.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0074.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0075.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0076.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0077.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0078.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0079.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0080.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0081.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0082.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0083.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0084.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0085.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0086.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0087.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0088.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0089.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0090.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0091.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0092.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0093.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0094.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0095.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0096.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0097.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0098.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0099.json",
  ]
