train_level_mode: list
train_levels_list:
  [
    "hard_pos_100_y_indix/grasp_hard_indepy_v0000.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0001.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0002.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0003.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0004.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0005.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0006.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0007.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0008.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0009.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0010.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0011.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0012.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0013.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0014.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0015.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0016.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0017.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0018.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0019.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0020.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0021.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0022.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0023.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0024.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0025.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0026.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0027.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0028.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0029.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0030.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0031.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0032.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0033.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0034.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0035.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0036.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0037.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0038.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0039.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0040.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0041.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0042.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0043.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0044.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0045.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0046.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0047.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0048.json",
    "hard_pos_100_y_indix/grasp_hard_indepy_v0049.json",
  ]
