train_level_mode: list
train_levels_list:
  [
    "grasp_hard_xvar_v0000.json",
    "grasp_hard_xvar_v0001.json",
    "grasp_hard_xvar_v0002.json",
    "grasp_hard_xvar_v0003.json",
    "grasp_hard_xvar_v0004.json",
    "grasp_hard_xvar_v0005.json",
    "grasp_hard_xvar_v0006.json",
    "grasp_hard_xvar_v0007.json",
    "grasp_hard_xvar_v0008.json",
    "grasp_hard_xvar_v0009.json",
    "grasp_hard_xvar_v0010.json",
    "grasp_hard_xvar_v0011.json",
    "grasp_hard_xvar_v0012.json",
    "grasp_hard_xvar_v0013.json",
    "grasp_hard_xvar_v0014.json",
    "grasp_hard_xvar_v0015.json",
    "grasp_hard_xvar_v0016.json",
    "grasp_hard_xvar_v0017.json",
    "grasp_hard_xvar_v0018.json",
    "grasp_hard_xvar_v0019.json",
    "grasp_hard_xvar_v0020.json",
    "grasp_hard_xvar_v0021.json",
    "grasp_hard_xvar_v0022.json",
    "grasp_hard_xvar_v0023.json",
    "grasp_hard_xvar_v0024.json",
    "grasp_hard_xvar_v0025.json",
    "grasp_hard_xvar_v0026.json",
    "grasp_hard_xvar_v0027.json",
    "grasp_hard_xvar_v0028.json",
    "grasp_hard_xvar_v0029.json",
    "grasp_hard_xvar_v0030.json",
    "grasp_hard_xvar_v0031.json",
    "grasp_hard_xvar_v0032.json",
    "grasp_hard_xvar_v0033.json",
    "grasp_hard_xvar_v0034.json",
    "grasp_hard_xvar_v0035.json",
    "grasp_hard_xvar_v0036.json",
    "grasp_hard_xvar_v0037.json",
    "grasp_hard_xvar_v0038.json",
    "grasp_hard_xvar_v0039.json",
    "grasp_hard_xvar_v0040.json",
    "grasp_hard_xvar_v0041.json",
    "grasp_hard_xvar_v0042.json",
    "grasp_hard_xvar_v0043.json",
    "grasp_hard_xvar_v0044.json",
    "grasp_hard_xvar_v0045.json",
    "grasp_hard_xvar_v0046.json",
    "grasp_hard_xvar_v0047.json",
    "grasp_hard_xvar_v0048.json",
    "grasp_hard_xvar_v0049.json",
    "grasp_hard_xvar_v0050.json",
    "grasp_hard_xvar_v0051.json",
    "grasp_hard_xvar_v0052.json",
    "grasp_hard_xvar_v0053.json",
    "grasp_hard_xvar_v0054.json",
    "grasp_hard_xvar_v0055.json",
    "grasp_hard_xvar_v0056.json",
    "grasp_hard_xvar_v0057.json",
    "grasp_hard_xvar_v0058.json",
    "grasp_hard_xvar_v0059.json",
    "grasp_hard_xvar_v0060.json",
    "grasp_hard_xvar_v0061.json",
    "grasp_hard_xvar_v0062.json",
    "grasp_hard_xvar_v0063.json",
    "grasp_hard_xvar_v0064.json",
    "grasp_hard_xvar_v0065.json",
    "grasp_hard_xvar_v0066.json",
    "grasp_hard_xvar_v0067.json",
    "grasp_hard_xvar_v0068.json",
    "grasp_hard_xvar_v0069.json",
    "grasp_hard_xvar_v0070.json",
    "grasp_hard_xvar_v0071.json",
    "grasp_hard_xvar_v0072.json",
    "grasp_hard_xvar_v0073.json",
    "grasp_hard_xvar_v0074.json",
    "grasp_hard_xvar_v0075.json",
    "grasp_hard_xvar_v0076.json",
    "grasp_hard_xvar_v0077.json",
    "grasp_hard_xvar_v0078.json",
    "grasp_hard_xvar_v0079.json",
    "grasp_hard_xvar_v0080.json",
    "grasp_hard_xvar_v0081.json",
    "grasp_hard_xvar_v0082.json",
    "grasp_hard_xvar_v0083.json",
    "grasp_hard_xvar_v0084.json",
    "grasp_hard_xvar_v0085.json",
    "grasp_hard_xvar_v0086.json",
    "grasp_hard_xvar_v0087.json",
    "grasp_hard_xvar_v0088.json",
    "grasp_hard_xvar_v0089.json",
    "grasp_hard_xvar_v0090.json",
    "grasp_hard_xvar_v0091.json",
    "grasp_hard_xvar_v0092.json",
    "grasp_hard_xvar_v0093.json",
    "grasp_hard_xvar_v0094.json",
    "grasp_hard_xvar_v0095.json",
    "grasp_hard_xvar_v0096.json",
    "grasp_hard_xvar_v0097.json",
    "grasp_hard_xvar_v0098.json",
    "grasp_hard_xvar_v0099.json",
  ]
