train_level_mode: list
train_levels_list:
  [
    "vary_joints_100/grasp_hard_joint_pos_var_v0000.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0001.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0002.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0003.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0004.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0005.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0006.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0007.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0008.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0009.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0010.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0011.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0012.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0013.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0014.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0015.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0016.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0017.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0018.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0019.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0020.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0021.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0022.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0023.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0024.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0025.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0026.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0027.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0028.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0029.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0030.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0031.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0032.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0033.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0034.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0035.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0036.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0037.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0038.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0039.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0040.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0041.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0042.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0043.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0044.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0045.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0046.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0047.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0048.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0049.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0050.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0051.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0052.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0053.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0054.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0055.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0056.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0057.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0058.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0059.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0060.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0061.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0062.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0063.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0064.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0065.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0066.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0067.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0068.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0069.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0070.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0071.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0072.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0073.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0074.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0075.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0076.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0077.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0078.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0079.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0080.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0081.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0082.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0083.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0084.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0085.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0086.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0087.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0088.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0089.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0090.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0091.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0092.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0093.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0094.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0095.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0096.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0097.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0098.json",
    "vary_joints_100/grasp_hard_joint_pos_var_v0099.json",
  ]
